site_name: Sat20

theme:
  # name: "material"
  # name: "gitbook"
  name: "readthedocs"
  # logo: "assets/logo.png"
  # favicon: "images/favicon.ico"
  language: "en"
  # features:
  #   - navigation.tabs
  #   - navigation.sections
  # palette:
  #   scheme: default
  custom_dir: overrides

nav:
  - SAT20 protocol:
      - "Overview": "introduce.md"
      - "Background": "why.md"
      - "Asset Issuance Protocol":
          - "Overview": "issuance/readme.md"
          - "Instructions": "issuance/instruct.md"
          - "Numbering of SAT: Ordinal": "issuance/ordinal.md"
          - "Read and Write of SAT: Inscribe": "issuance/inscribe.md"
          - "Asset Issuance Models": "issuance/model.md"
          - "SAT Objects": "issuance/sob.md"
          - "Name Service (SNS)": "issuance/SNS.md"
          - "D-Indexer": "issuance/d-indexer.md"
          - Scenarios:
              - "FT": "issuance/cases/FT.md"
              - "NFT": "issuance/cases/NFT.md"
              - "SFT": "issuance/cases/SFT.md"
              - "DID": "issuance/cases/DID.md"
              - "DeIP": "issuance/cases/DeIP.md"
      - "Asset Circulation Protocol":
          - "Overview": "circulation/readme.md"
          - "SAT Locking": "circulation/satlock.md"
          - "SAT Transcending": "circulation/sattranscend.md"
          - "SAT Swapping": "circulation/satswap.md"
          - "Enhanced UTXO": "circulation/enUTXO.md"
          - "Client Verification": "circulation/CA.md"
          - "SVM": "circulation/SVM.md"
          - Scenarios:
              - "DEX": "circulation/cases/sdex.md"
              - "MPC": "circulation/cases/MPC.md"
              - "DePIN": "circulation/cases/DePIN.md"
  - Samples: sample.md
  - Roadmap: roadmap.md
  - API: https://apiprd.ordx.space/mainnet/swagger/index.html
  - Donate: donate.md
  - About: about.md
  - 中文: /index.html

plugins:
  - search
  - mkdocstrings
